# Generated by Django 4.2.13 on 2024-12-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("role", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sysrolemenu",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="role.sysrole"
            ),
        ),
    ]
